version: '3.7'

services: 
  frontend:
    build: 
      context: ../frontend
      dockerfile: Dockerfile
    ports: 
      - 8000:80
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
  
  postgres:
    image: postgres
    environment: 
      - POSTGRES_DB=capiflix
      - POSTGRES_PASSWORD=capiflix
    volumes:
      - db-capiflix:/var
  
volumes:
  db-capiflix: