FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

WORKDIR /src

COPY ["Api.Capiflix/Api.Capiflix.csproj", "Api.Capiflix/"]
COPY ["Business/Business.csproj", "Business/"]
COPY ["BusinessApi/BusinessApi.csproj", "BusinessApi/"]
COPY ["Domain/Domain.csproj", "Domain/"]
COPY ["ImportData/ImportData.csproj", "ImportData/"]
COPY ["Tests/Tests.csproj", "Tests/"]


COPY . .

WORKDIR /src

RUN dotnet restore "Capiflix.sln"
RUN cd Tests

CMD [ "dotnet", "test" ]